## Лабораторная работа №0 (NumPy)

Выполнил: Новицкий Никита (6132-010402D)

In [1]:
import numpy as np

Взять из документации по numpy 12 любых функций / методов / операторов и продемонстрировать их работу. Для каждой функции добавить комментарий.

In [2]:
# Для начала сгенирируем массивы, который будем использовать для выполнения первого задания
arr1, arr2 = np.random.randn(3, 3), np.random.randn(3, 3)

In [3]:
arr1

array([[ 1.14353432, -0.91432677,  1.97025236],
       [ 2.28490208, -1.25958194, -0.36805586],
       [-0.11315207,  0.3953461 , -0.0353363 ]])

In [4]:
# Максимальное значение в массиве
arr1.max()

2.284902084749465

Чтобы мы могли понять, что делает та или иная функция мы будем использовать следующую конструкцию: ?np.max (будет появляться окошко, где подробно будет описано, что это за функция и для чего она нужна)

In [ ]:
?np.max

In [5]:
# Минимальное значение в массиве
arr1.min()

-1.2595819364141254

In [ ]:
?np.max

In [6]:
# Транспонирование массива
arr1.T

array([[ 1.14353432,  2.28490208, -0.11315207],
       [-0.91432677, -1.25958194,  0.3953461 ],
       [ 1.97025236, -0.36805586, -0.0353363 ]])

In [ ]:
?np.transpose

In [7]:
# Сортировка массива
np.sort(arr1)

array([[-0.91432677,  1.14353432,  1.97025236],
       [-1.25958194, -0.36805586,  2.28490208],
       [-0.11315207, -0.0353363 ,  0.3953461 ]])

In [ ]:
?np.sort

In [8]:
# Размерность массива
arr1.shape

(3, 3)

In [ ]:
?np.shape

In [9]:
# Определитель матрицы
np.linalg.det(np.random.randn(5, 5))

-3.4624920197505173

In [ ]:
?np.linalg.det

In [10]:
# Решение СЛАУ с помощью NumPy
A = np.random.randn(3, 3)
B = np.random.randn(3, 1)
np.linalg.solve(A, B)

array([[ 0.05809638],
       [ 0.92703732],
       [-0.22447447]])

In [ ]:
?np.linalg.solve

In [11]:
# Матричное произведение
np.matmul(arr1, arr2)

array([[ 1.44843418,  0.42594984,  1.37048104],
       [ 0.45966347, -0.04123357, -1.1693023 ],
       [ 0.34043458,  0.12552982,  0.48291852]])

In [ ]:
?np.matmul

In [12]:
# Обратная матрица
np.linalg.inv(arr1)

array([[ 0.11843839,  0.46536954,  1.75659367],
       [ 0.07628331,  0.11377077,  3.0683279 ],
       [ 0.47420804, -0.21730332,  0.40437925]])

In [ ]:
?np.linalg.inv

In [13]:
# Объединение массивов
np.stack((arr1, arr2))

array([[[ 1.14353432, -0.91432677,  1.97025236],
        [ 2.28490208, -1.25958194, -0.36805586],
        [-0.11315207,  0.3953461 , -0.0353363 ]],

       [[ 0.98346883,  0.25176485,  0.46645151],
        [ 1.20735254,  0.41296834,  1.45326478],
        [ 0.72463741,  0.26171068,  1.09926864]]])

In [ ]:
?np.stack

In [14]:
# Найдем индекс максимального элемента в массиве
np.argmax(arr1)

3

In [ ]:
?np.argmax

In [15]:
# Выведем информацию по массиву
np.info(arr2)

class:  ndarray
shape:  (3, 3)
strides:  (24, 8)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x6000002112c0
byteorder:  little
byteswap:  False
type: float64


In [ ]:
?np.info

Сгенерировать OLAP-куб, где фиксируем продажи товаров в розничной сети по магазинам. Оси: 0: ID группы товаров 1: ID магазина 2: день месяца, в котором осуществляются продажи (предположим у нас в OLAP-кубе собраны продажи за месяц).

Содержимое ячейки: продажи в тыс. рублей данной категории товаров в данном магазине в данный день.

Рекомендуется сгенерировать статистически-правдопододные данные в ячейках. К примеру, будет странно, если продажи одной и той же группы товаров в соседние дни будут представлять из себя "белый шум". Пусть будет какой-то правдоподобное распределение на ваш вкус. Также продажи одних и тех же групп товаров в разных магазинах не могут отличаться в сотни и тысячи раз, максимум в разы. Подумайте как это обыграть используя различные функции генерации случайных чисел + "смекалку".

In [16]:
products = np.arange(0, 22, 1)
shops = np.arange(0, 5, 1)
days = np.arange(1, 31, 1)
cube = np.zeros([products.size, shops.size, days.size])

for p in range(products.size):
    for s in range(shops.size):
        for d in range(days.size):
            cube[p, s, d] = np.random.randint(10, 80)

In [17]:
cube

array([[[30., 55., 18., ..., 14., 70., 55.],
        [28., 15., 60., ..., 28., 28., 11.],
        [59., 15., 50., ..., 71., 78., 20.],
        [60., 66., 42., ..., 42., 11., 70.],
        [43., 12., 33., ..., 10., 12., 48.]],

       [[54., 64., 68., ..., 66., 60., 32.],
        [66., 74., 42., ..., 31., 35., 30.],
        [40., 76., 43., ..., 42., 16., 12.],
        [32., 64., 63., ..., 66., 49., 68.],
        [49., 74., 56., ..., 14., 28., 32.]],

       [[77., 64., 62., ..., 24., 51., 50.],
        [59., 14., 35., ..., 56., 63., 44.],
        [74., 12., 65., ..., 74., 21., 32.],
        [47., 50., 10., ..., 67., 51., 37.],
        [62., 24., 60., ..., 41., 17., 26.]],

       ...,

       [[75., 75., 64., ..., 12., 56., 68.],
        [46., 40., 46., ..., 45., 11., 48.],
        [10., 53., 73., ..., 36., 26., 36.],
        [24., 57., 69., ..., 72., 36., 56.],
        [53., 44., 77., ..., 20., 51., 48.]],

       [[56., 34., 57., ..., 20., 57., 61.],
        [20., 18., 28., ..., 20., 

Для получившегося OLAP-куба посчитать суммарные, средние, минимальные и максимальные продажи (на самом деле любые агрегатные функции можно использовать)зафиксировав значения по одной, двум или трём осям:

Например взять какой-то определённый набор товаров и набор городов или диапазон дней и сагрегировать данные по всем ячейкам из зафиксированного набора. Пример: получить сумму, среднее, минимум и максимум по продажам 10-20 чисел месяца для товаров [1,3,4] по всем городам (или по конкретному набору городов).

Попробуйте различные варианты индексации и различные варианты срезов, насколько хватит фантазии.

In [18]:
print("Общая сумма продаж всех товаров во всех магазинах за весь месяц: \n")
print(np.sum(cube[:, :, :]))
print("Сумма по продажам 7-9 чисел месяца для товара 7 по всем магазинам: \n")
print(np.sum(cube[7, :, [days[6:8]]]))
print("Минимум по продажам 10-20 чисел месяца для товара 16 в магазине 3: \n")
print(np.min(cube[16, 3, [days[9:20]]]))
print("Минимум по продажам 15-20 чисел месяца для товара 7 в магазине 4: \n")
print(np.min(cube[7, 4, [days[14:20]]]))
print("Стандартное отклонение по продажам 1-10 чисел месяца для товара 4 по всем магазинам: \n")
print(np.std(cube[4, :, [days[0:10]]]))
print("Максимум по продажам за все время для товара 9 в магазине 3: \n")
print(np.max(cube[9, 3, :]))
print("Cреднее по продажам за все время для товара 2 в магазине 2: \n")
print(np.mean(cube[2, 2, :]))

Общая сумма продаж всех товаров во всех магазинах за весь месяц: 

149796.0
Сумма по продажам 7-9 чисел месяца для товара 7 по всем магазинам: 

442.0
Минимум по продажам 10-20 чисел месяца для товара 16 в магазине 3: 

14.0
Минимум по продажам 15-20 чисел месяца для товара 7 в магазине 4: 

23.0
Стандартное отклонение по продажам 1-10 чисел месяца для товара 4 по всем магазинам: 

19.73606850413729
Максимум по продажам за все время для товара 9 в магазине 3: 

77.0
Cреднее по продажам за все время для товара 2 в магазине 2: 

49.53333333333333
